### ISSUE TITLE
Doing a Roadmap

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#261]
The last thing missing from Mozilla Working Open Workshop is doing a roadmap about where we would like to go, see mozillascience/working-open-workshop/issues/43. Let's collect some ideas here or [in a pad](https://gedankenstuecke.piratenpad.de/opensnp-roadmap).

**Comment by acabunoc** [comment]
Let me know if you need any help here! Happy to take a look :)

**Comment by gedankenstuecke** [comment]
@acabunoc thanks so much. We'll definitely come back to that once we have some content there!

@philippbayer see the output of todays call with @acabunoc here https://public.etherpad-mozilla.org/p/wow-bastian We also discussed shifting it to 5pm Toronto time, so we can all participate in the next call, you should have a calendar invite from me. :smile:

**Comment by gedankenstuecke** [comment]
**And here we go!**

Timeline:
Feb
- [ ] Write a roadmap
- [ ] Research hackathons - where can you bring OpenSNP

March
- [ ] Persona exercise - ideal contributor for these new features https://gedankenstuecke.piratenpad.de/mozwow-personas
- [ ] Reach out to the organisations found in Feb

April
- [ ] Promo blasts - emailing lists, tweeting
- [ ] FORCE portland - http://ruleofthirds.de/scholarly-commons/ 

May
- [ ] Mini sprints -- a bunch of local ones?

June
- [ ] 2-3 Global Sprint

**Comment by acabunoc** [comment]
Do you have a roadmap for your product? Like implementing features / addressing issues by a certain point? I see a bit of that here: https://gedankenstuecke.piratenpad.de/opensnp-roadmap

**Comment by gedankenstuecke** [comment]
Nope, no specific timelines so far. I think we rather focussed on getting more contributors today. :smile:

**Comment by acabunoc** [comment]
I'd encourage you to have a product roadmap so that contributors know where they can help today and understand your long term plan! 

No need to set hard dates, but helpful for getting involved.

**Comment by gedankenstuecke** [comment]
Okay, @philippbayer would you be up to prioritizing the roadmap list together with me? :)

**Comment by acabunoc** [comment]
Thanks both! Just break down your development goals into smaller tasks and map them along some sort of timeline :)

I think you did a lot of this in the pad above^
