### ISSUE TITLE
Support for Genes for Good

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#290]
The [University of Michigan has the project *Genes for Good*](https://genesforgood.sph.umich.edu). We already have some of their data sets on openSNP (i.e. genotype IDs 3414, 3486, 3516, 3517). While the format is in principle the same as the one by *23andMe* we should at least think about whether we want to add them to the supported data providers and give them an extra label. 

I think there are two possible options that we could do (and I think we should go for at least one of them over doing nothing): 

1. Just extend the front-end label when uploading to make it display "*23andMe/Genes for Good*" and let it be
2. Add an extra label/category for *Genes for Good*, and just use the *23andMe* parser in the backend for reading in the files.

I personally do have a small tendency to prefer the latter option. I think having a clear indicator of where the data originated is more useful. And it also would make the people of *Genes for Good* feel more welcome in a way I assume.

## Todo:

- [x] Decide on one of the options

- [x] Implement the new data type on backend
- [x] Add the new data type to front end 
- [x] Add a section about it on the FAQ
- [x] Add the new data type to worker/queue routines -> redirect to 23andMe

**Comment by philippbayer** [comment]
:+1: for "Add an extra label/category for Genes for Good, and just use the 23andMe parser in the backend for reading in the files", it's the least confusing option for the user IMHO

**Comment by philippbayer** [comment]
I just realized that you'd also need to add the filetype with a small example to the [filetypes FAQ](https://www.opensnp.org/faq#filetypes)

**Comment by gedankenstuecke** [comment]
closed by #294
